name: Build

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: |
          dotnet restore
          dotnet tool restore
      - name: Format check
        run: dotnet format --verify-no-changes --verbosity normal
      - name: Build
        run: dotnet build --no-restore
      - name: Migration check
        run: dotnet ef migrations has-pending-model-changes
        working-directory: ./FundRaisingAssignment.Application
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRINGS }}
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRINGS }}
      - name: Publish Test Result
        uses: dorny/test-reporter@v3.0.0
        if: always()
        with:
          name: .NET Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx